# nixpacks.toml
[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm ci",
  # use npm install in client unless you guarantee a client lockfile
  "cd client && npm install"
]

[phases.build]
cmds = [
  "rm -rf client/dist client/node_modules/.cache",
  "cd client && npm run build",
  "ls -la client/dist",
  "cat client/dist/asset-manifest.json || true"
]

[start]
cmd = "node server.js"

[variables]
NODE_ENV = "production"
# Optionally bake this for CRA. Replace with your Railway URL.
# REACT_APP_API_URL = "https://<your-api-or-app-domain>"