[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = ["npm ci", "cd client && npm ci"]

[phases.build]
cmds = [
  "rm -rf client/build client/node_modules/.cache",
  "cd client && npm ci",
  "cd client && npm run build"
]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"